### PR TITLE
Changes in Edit page

### PR DESCRIPTION
**Pull request by mxwell**
I think Edit page could be improved in terms of uniformity and size. Here are my suggestions, please review.

### CODE REVIEW

**Comment by Armadill0** [comment]
The intention I set the default priority to the value "3" is, that it is easier to move tasks which have a lower priority to the end of the list. As an example: If you have a list with 10 items and you want to move one of those to the end because of a low priority and the default priority is "1" then you have to increase the priority of 9 tasks, which is quite annoying.
With the mid value of "3" for the priority you only have to set a new priority to this one task. And you still have the possibility to prioritize tasks highe with two more levels.
This is also the reason why I changed the priority reporesentation to --, -, "", + and ++. It shows the user that the default priority is "normal" while other values declare lower, lowest, higher and highest priority.

I also like the slider holding to set the priority because you have a quick overview which priorities are available. Although I must admit, that I forgot to replace the raw numbers of the priority by the labels which are used on the TaskPage. My bad. :anguished: 

And last but not least the reason why I added the taskname of the task to the DialogHeader is to be able to see the title of the task regardless if I already changed or erroneously removed it's name and forgot it myself. So I can see it anyway and don't have to leave the Dialog discarding my changes a wanted to make.
But I'm with you, that the Dialog header takes to much room on the small smartphone display (I was really agry when they changed the DialogHeader's location out of the topbar...). I'm thinking of moving it to the taskname textfield's label below ("(currently: <taskname>)" or something like that).

Just my 2 cents. We could also meet on Freenode IRC, I'm always available (regarding normal UTC+2 day times) in #sailfishos. :smile:

**Comment by mxwell** [comment]
1. The first commit is not about the default value :smile: 
2. Edit page has a variety of elements, and I wanted to eliminate some of them, to get more uniformity. Sliders hardly go along with the other elements. Also a page with sliders in the bottom part of the screen makes gesture 'swipe to the side' meaningless. You could compare it with the main page of Settings app: there are only 3 types of elements, they are grouped together and sliders are placed in the top half. There is also a vast empty space (!) in the middle to divide sliders and menu.
3. I understand your intention with a task title, but displaying anything two times is a waste of screen area. Please, clarify your case. Imho, any task changes are quite smallish and it's not a big deal to lose them and start over. That is not an essay.

And please try this version in action on a real device, you may like it.

**Comment by Armadill0** [comment]
1. Haha, this is quite embarassing. :laughing: 
2. I'll give it a try. :wink: 
3. I'll also think about this.

**Comment by Armadill0** [comment]
Ok, I merged your changes. However I'll add some slight changes which replaces the Edit task label at the top of the page again with the DialigHeader title, because I think the differences are very minor, but the hightlight color of the text marks it as a headline. It also needs less code. :smile: 

Is this compromise ok for you?

Additionally you have to be carefully, if you're changing the default text of translation IDs. This could possibly change all translations for the edit-label (which is used in many other contexts, too) in the whole application! So simply change it to another ID and everything's cool. :wink:

**Comment by mxwell** [comment]
Thank you. But it seems the translation of 'edit-task-label' is lost indeed: I needed to run ./gen-ts.sh, add translation with linguist and run ./gen-qm.sh, before the dialog header appears normally.

**Comment by Armadill0** [comment]
Don't worry, the "edit-task-label" has been created by me. So it's normal that there's currently no label available for it. :smile:

**Pull request merged**
