### PR TITLE
Creation of a task

### PR DESCRIPTION
**Pull request by mxwell**
After discussion in #55 I've tried to add Remorse, but the standard RemorseItem appends "in N seconds" to the message (that could look like "Tap to add details") and it doesn't make much sense :smiley: 

I figured blinking of some kind is not a bad idea, so I've implemented it. Please, check it out. It's just an experiment, feel free to modify or even discard the feature.

### CODE REVIEW

**Comment by Armadill0** [comment]
This is a really cool idea! :+1: :smile: 

I'll do some more testing this evening, but it looks very nice and I really like this instead of adding another pull down menu option!

**Comment by Armadill0** [comment]
I recently increased the duration/blinks to 2250/9. This seems a bit more attracting. What do you think?

**Comment by mxwell** [comment]
If under 2250 you mean a multiplier, then yes, it would attract more attention.

**Comment by Armadill0** [comment]
I'm speaking of this line: https://github.com/mxwell/harbour-tasklist/blob/3a15d557a4d6eed2a62b132b32ecd114111f76f8/qml/pages/TaskPage.qml#L575
:wink:

**Comment by Armadill0** [comment]
I just commited the changes I've done, so you can try it out on the next branch. :smile:

**Pull request merged**
