### PR TITLE
Dropbox support

### PR DESCRIPTION
**Pull request by mxwell**
It is an implementation of #50. 

Keeping API keys in repository is "considered harmful", so I suggest providing them as arguments for qmake. In QtCreator it's basically a string in Projects tab, under "Build steps" -> "qmake" -> "Additional arguments". You need to put there two values in the following form to build the app:

```
TASKLIST_DROPBOX_APPKEY=<..> TASKLIST_DROPBOX_SHAREDSECRET=<..>
```

If necessary, I can share my keys for testing purposes.

So please take a look. You will probably want to rework UI in your style. Feel free to ask any questions.

### CODE REVIEW

**Comment by Armadill0** [comment]
I have problems to run a test in the SDK virtual machine.

I added the API keys as QMakeOptions in the yaml file, but it doesn't seem to work. How did you provide the keys to get it working in the SDK?

**Comment by mxwell** [comment]
Do you mean "rpm/harbour-tasklist.yaml"? It's tracked by git, and doesn't seem a good place for API keys.

I set keys in QtCreator's "Projects" tab for each kit there (ARM- and x86-based), details are in the first message. There is also the field "Effective qmake call", which displays actual command. Eventually they end up in the file "harbour-tasklist.pro.user" like this:

```xml
<value type="QString" key="QtProjectManager.QMakeBuildStep.QMakeArguments">TASKLIST_DROPBOX_APPKEY=xxxxxxxxxxxxxxx TASKLIST_DROPBOX_SHAREDSECRET=xxxxxxxxxxxxxxx</value>
```

After that you should be able to finish a build.

I couldn't find what is the best way to provide sensitive information into build process, so probably there are better ways.

**Comment by Armadill0** [comment]
Yes I know the yaml is a bad place to keep the keys. I just wanted to do a quick test. :wink: 

The project configuration seems to be a good place for that. I'll keep on eye on the changes in the next commit, if the keys are stored somewhere they shouldn't be stored. :smile:

**Comment by Armadill0** [comment]
You're right, it's stored in the pro.user file. But this is already in the .gitignore, so this shouldn't be an issue. :smile:

**Pull request merged**
