### PR TITLE
Closed tasks appearance

### PR DESCRIPTION
**Pull request by mxwell**
PR introduces an option to hide closed tasks besides the current options to (un)select switch and strike it through.

If one wants to keep tasks (e.g. for history), but doesn't want to see them around, then I figured this option could be helpful.

Please review.

### CODE REVIEW

**Comment by Armadill0** [comment]
I'll have alook on this asap.

**Comment by Armadill0** [comment]
Damn I accidentally deleted my comment at your commit. I hope you got an email and still have the problem I discovered. :smile:

**Comment by mxwell** [comment]
Thanks, there was a typo.

**Comment by Armadill0** [comment]
Yes now it works. But after changing from or to "hide" the items don't appear or disappear. Interesting: If I change from strike-through to hide, they don't hide, but are not striked-through. :smile:

**Comment by mxwell** [comment]
Now option is tracked and is effective immediately. Please review :-)

**Comment by Armadill0** [comment]
Looks very good. :smile:

**Pull request merged**
