### PR TITLE
More features for v2.0

### PR DESCRIPTION
**Pull request by mxwell**
Hey Armadill0!

More features are added. They related to issues #21, #34, #37, #39, but I forgot to mention them in commits.

Please review and test them when you've got time. Don't forget to back up your data :smile: And feel free to change layouts and texts if you see ways for improvement

### CODE REVIEW

**Comment by Armadill0** [comment]
I'm currently reviewing the changes. I already have some things, which I want to change. So this will take a while to be reviewed completely.

**Comment by mxwell** [comment]
Any updates about the reviewing?

**Comment by Armadill0** [comment]
I gave it a short try some weeks ago, but had no time to have a deeper look into it due to many other projects.

I hope I can do this soon (TM). :wink:

**Comment by Armadill0** [comment]
Alright, there are a few things I want/need to change before I'll merge it to the master branch.

For testing purposes it would be handy to have the pull-request in another branch. But I'm not able to change the target branch of your pull request.
So, could you please change the target branch to "next" instead of "master"? (I dont' know if you can change this or if this has to be done with a new pull request.)

Sorry for the inconveniences.

**Pull request closed without merging**
